---
title: "demo"
output: html_document
---

```{r}

rm(list=ls())

############################## myfunction
getStat <- function(data1, data0){
  a1 <- cor(data1); diag(a1)<-0
  a0 <- cor(data0); diag(a0)<-0
  ngroup <- dim(a1)[1]
  temp0 <- a0; temp1 <- a1
  temp0[which(temp0>=0)]<-0;temp0[which(temp0<0)]<-1;
  temp1[which(temp1>=0)]<-0;temp1[which(temp1<0)]<-1;
  temp <- abs(temp0-temp1)
  A0 <- a0^6; A1 <- a1^6
  A0[which(temp==0)]<--A0[which(temp==0)]
  d.node <- abs(A0+A1)
  t.edge <- d.node[lower.tri(d.node, diag=FALSE)]
  t.node <- as.vector(rowsum(d.node,group=rep(ngroup,ngroup)))
  t <- list(t.edge=t.edge,t.node=t.node,deltaA=d.node)
  return(t)
}


############################## load a dataset: feature * sample
load(file='~/Desktop/NetTDPcode/myDataAD.Rdata')
load(file="~/Desktop/NetTDPcode/ADPermuID.RData")
ExpDat <- t(ExpDatAD[1:1000,])
datC1 <- scale(ExpDat[rownames(ExpDat)=='Control',])
datC2 <- scale(ExpDat[rownames(ExpDat)=='AD',])
```



```{r}
############################# TDP inference for the whole co-expression network
t.obs <- getStat(datC1,datC2)
Nodediff.Obs.abs <- t.obs$t.node
Edgediff.Obs.abs <- t.obs$t.edge
b <- 199
ngenes <- dim(ExpDat)[2]
Nodediff.Perm.abs <- matrix(,nrow = b,ncol = ngenes)
Edgediff.Perm.abs <- matrix(NA, ncol=(ngenes^2 - ngenes)/2, nrow=b)

for (i in 1:b) {
  print(paste("i = ", i))
  C1 <- ExpDat[permuID[,i]=="Control",]
  C2 <- ExpDat[permuID[,i]=="AD",]
  t <- getStat(C1,C2)
  Nodediff.Perm.abs[i,] <- t$t.node
  Edgediff.Perm.abs[i,] <- t$t.edge
}

G.abs.node <- rbind(Nodediff.Obs.abs,Nodediff.Perm.abs)
G.abs.edge <- rbind(Edgediff.Obs.abs,Edgediff.Perm.abs)

library(sumSome)
myalpha <- 0.05
######## node-level inference
G<-G.abs.node
res.abs.node <- tdp(sumStats(G, alpha = myalpha))
print(paste('lower (1-alpha)-confidence bound for the number of true discoveries in the set is',res.abs.node))
######## edge-level inference
G<-G.abs.edge
nEdge <- dim(G)[2]
k <- ceiling(nEdge * 200 * myalpha)
thr <- sort(as.vector(G), decreasing=TRUE)[k]   # threshold: k-th greatest statistic
res.abs.edge <- tdp(sumStats(G, alpha = myalpha, truncFrom = thr, truncTo = 0))
print(paste('lower (1-alpha)-confidence bound for the number of true discoveries in the set is',res.abs.edge))

```


```{r}
############################# gene module detection
library(WGCNA)
AdjDiff <- t.obs$deltaA
########### parameters setting
# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 30;
myclusterMethod = "ward.D2";
MEDissThres = 0.4
ExpMatrix <- ExpDat
# Turn adjacency into topological overlap
TOM = TOMsimilarity(AdjDiff);
dissTOM = 1-TOM
# Call the hierarchical clustering function
geneTree = hclust(as.dist(dissTOM), method = myclusterMethod);
# Plot the resulting clustering tree (dendrogram)
sizeGrWindow(12,9)
plot(geneTree, xlab="", sub="", main = "Gene clustering on TOM-based dissimilarity",
     labels = FALSE, hang = 0.04);
# Module identification using dynamic tree cut:
dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM,
                            deepSplit = 4, pamRespectsDendro = FALSE,
                            minClusterSize = minModuleSize);
table(dynamicMods)
# Convert numeric lables into colors
dynamicColors = labels2colors(dynamicMods)
table(dynamicColors)
# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05,
                    main = "Gene dendrogram and module colors")
moduleColors = dynamicColors
# Construct numerical labels corresponding to the colors
moduleLabels = dynamicMods
# Calculate eigengenes
MEList = moduleEigengenes(ExpMatrix, colors = dynamicColors)
MEs = MEList$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss = 1-cor(MEs);
# Cluster module eigengenes
METree = hclust(as.dist(MEDiss), method = myclusterMethod);
# Call an automatic merging function
merge = mergeCloseModules(ExpMatrix, dynamicColors, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors = merge$colors;
# Eigengenes of the new merged modules:
mergedMEs = merge$newMEs;
sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors),
                    c("Dynamic Tree Cut", "Merged dynamic"),
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
#dev.off()
# Rename to moduleColors
moduleColors = mergedColors
# Construct numerical labels corresponding to the colors
colorOrder = c("grey", standardColors(50));
moduleLabels = match(moduleColors, colorOrder)-1;
MEs = mergedMEs

############################# TDP inference for sub-network
cluster <- unique(moduleColors)
ncluster <- length(cluster)
tdp.abs.node <-  c()
G<-G.abs.node
for (i in 1:ncluster) {
  print(paste('i =', i))
  mysubset <- which(moduleColors==cluster[i])
  res.abs <- sumStats(G,mysubset,alpha = myalpha)
  tdp.abs.node[i] <- tdp(res.abs) 
}


G<-G.abs.edge
adj <- matrix(0,ngenes,ngenes)
tdp.abs.edge <-  c()
for (i in 1:ncluster) {
  print(paste('i =', i))
  mysubset <- which(moduleColors==cluster[i])
  adj.temp <- adj
  adj.temp[mysubset,mysubset] <-1
  vec <- adj.temp[upper.tri(adj.temp)]
  mysubset.edge <- which(vec==1)
  res.abs <- sumStats(G, S = mysubset.edge, alpha = myalpha,truncFrom = thr, truncTo = 0)
  tdp.abs.edge[i] <- tdp(res.abs)
}
```





